# -*- coding: utf-8 -*-
"""Reto 1.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/14uLp4lN74pDPJmvhYYSrZN2cpr-CNf5t
"""

J67=int(input())
M15=int(2*J67+4)
R99=int((M15+J67)/5)
print(str(J67)+" "+str(M15)+" "+str(R99))
nivel_de_toxicidad_1="uno"
nivel_de_toxicidad_2="dos"
nivel_de_toxicidad_3="tres"
nivel_de_toxicidad_4="cuatro"
if R99>80:
  print(nivel_de_toxicidad_4)
if 41<=R99<=80:
  print(nivel_de_toxicidad_3)
if 21<=R99<=40:
  print(nivel_de_toxicidad_2)
if 0<=R99<=20:
  print(nivel_de_toxicidad_1)