# -*- coding: utf-8 -*-
"""reto2.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1xDhV3VWE4P9J84SP5nQYDyFgGtHI1Bgj
"""

print("lista de productos de aseo: ")
productos_aseo=input()
print("lista de productos de belleza: " )
productos_belleza=input()
print("lista de productos vendido:")
mas_vendido_belleza="B"
mas_vendido_aseo="A"
empate="E"
productos_vendidos=input()
contador_1=0
contador_2=0
for letra in productos_vendidos:
  if letra in productos_aseo:
    contador_1+=1
    #print("productos vendidos de aseo= ",contador_1)
  else:
   contador_1+=0
   #print("productos vendidos de aseo= ", contador_1)
  if letra in productos_belleza:
    contador_2+=1
    #print("productos vendidos de belleza= ", contador_2)
  else:
    contador_2+=0
    #print("productos vendidos de belleza= ",contador_2)
  if contador_1<contador_2:
    print(mas_vendido_belleza,end="")
  if contador_1==contador_2:
    print(empate,end="")
  if contador_1>contador_2:
    print(mas_vendido_aseo,end="")